# Generated by Django 6.1.1 on 2026-10-05 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120, verbose_name='Nombre del negocio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('zone', models.CharField(max_length=100, verbose_name='Zona / barrio')),
                ('schedule', models.CharField(blank=True, help_text='Ej: Lun a Sáb, 8:00 a 18:00', max_length=120, verbose_name='Horario')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('vet', 'Veterinaria'), ('grooming', 'Peluquería'), ('walk', 'Paseo'), ('sitting', 'Cuidado temporal')], max_length=10, verbose_name='Tipo de servicio')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('reference_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio de referencia (COP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
